{
    "name": "Accounting",
    "summary": "Invoices, Contracts & Payments",
    "author": "Onestein",
    "category": "Accounting",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "depends": [
        "account",
        "account_payment_mode",
        "account_payment_order",
        "account_payment_partner",
        "account_fiscal_position_vat_check",
        "account_invoice_constraint_chronology",
        "account_invoice_line_default_account",
        "account_journal_lock_date",
        "account_lock_date_update",
        "account_move_print",
        "account_usability",
        "account_reconcile_oca",
        "account_statement_base",
        "account_payment_sale",
        "product_margin",
        "account_financial_report",
        "product_category_product_link",
        "account_statement_import_camt",
        "account_statement_import_camt54",
        "account_statement_import_file_reconcile_oca",
        "account_period_auto_create",
        "account_statement_import_online_ponto",
        "account_statement_import_online_ponto_statement_creation_mode",
        "account_statement_import_sheet_file",
        "account_statement_import_sheet_file_sheet_mappings",
        "account_move_line_attachment_preview",
        "account_configuration",
        "account_invoice_overdue_reminder",
        "account_move_line_tax_editable",
        "account_move_tier_validation",
        "account_statement_import_online_paypal",
        "contract",
        "contract_payment_mode",
        "currency_rate_update",
        "mollie_account_sync",
        "partner_manual_rank",
        "payment_mollie_official",
        "mis_builder",
        "mis_builder_budget",
        "account_operating_unit",
    ],
    "bundle": True,
}
