{
    "name": "Membership Management",
    "summary": "Efficiently manage memberships and administrative tasks",
    "author": "Onestein",
    "website": "https://onestein.nl",
    "category": "Membership",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "data": ["security/security.xml"],
    "depends": [
        "membership",
        "membership_branding",
        "membership_contribution",
        "membership_extension",
        "membership_prorate",
        "membership_subscription",
        "membership_variable_period",
        "membership_group",
        "sale_recurring_payment_mollie",
        "subscription_portal",
    ],
    "bundle": True,
}
