{
    "name": "Essentials Installation",
    "summary": "Installs essential modules",
    "author": "Onestein",
    "website": "https://onestein.nl",
    "category": "Technical",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "data": ["security/security.xml"],
    "depends": [
        "base_address_extended",
        "base_technical_features",
        "fs_storage",
        "fs_attachment",
        "fs_storage_backup",
        "web_responsive",
        "web_pwa_oca",
        "disable_odoo_online",
        "base_fontawesome",
        "auth_oidc",
        "container_accessibility",
        "report_qr",
        "report_qweb_parameter",
        "report_wkhtmltopdf_param",
        "report_xlsx",
        "report_xlsx_helper",
        "date_range",
        "base_tier_validation",
        "digest_configuration",
        "payment_custom",
        "payment_demo",
        "partner_firstname",
        "web_no_bubble",
        "base_customer_company",
        "base_customer_user",
        "base_onboarding",
        "spreadsheet_dashboard_oca",
        "spreadsheet_oca_ux",
        "remove_odoo_enterprise",
        "base_import_debranding",
        "digest_disable",
        "partner_external_map",
        "fetchmail_notify_error_to_sender",
        "product_category_product_link",
        "mail_debrand",
        "base_module_bundle",
        "mail_attach_existing_attachment",
        "partner_contact_department",
        "mail_tracking",
        "mail_raise_log_level",
        "sentry",
    ],
    "bundle": True,
}
