name: dev-build

on:
  push:
    branches:
      - "16.0"

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tags: ghcr.io/${{ github.repository_owner }}/curq:dev,ghcr.io/${{ github.repository_owner }}/curq:${{ github.sha }}
