name: migration

on:
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      to:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Prepare env files
        run: |
          MODULES=$(docker run ${{ inputs.from }} -c "manifestoo -d /odoo/custom list | grep _install | paste -sd,")
          cat > .env.base <<EOF
          DB_HOST=localhost
          DB_PORT=5432
          DB_USER=odoo
          DB_PASSWORD=odoo
          MODULES=$MODULES
          WORKERS=0
          MODE=InstallOnly
          DOCKER=true
          DB_NAME=main
          DB_FILTER=^main$
          EOF
      - name: Initialize ${{ inputs.from }}
        run: |
          docker volume create fs
          docker run \
            --volume fs:/odoo/data \
            --network=host \
            --entrypoint /usr/local/bin/entrypoint.sh \
            --env-file .env.base \
            ${{ inputs.from }}
      - name: Test update
        run: |
          docker run \
            --volume fs:/odoo/data \
            --network=host \
            --entrypoint /usr/local/bin/entrypoint.sh \
            --env-file .env.base \
            --env MODE=UpdateOnly \
            ${{ inputs.to }}
