name: test-build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "16.0"
jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tags: ghcr.io/${{ github.repository_owner }}/curq-ci:pr-${{ github.event.pull_request.number }}
      target: "ci"
  test:
    runs-on: ubuntu-22.04
    needs: [build]
    container: 
      image: ghcr.io/${{ github.repository_owner }}/curq-ci:pr-${{ github.event.pull_request.number }}
    services:
      postgres:
        image: postgres:13.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      DB_HOST: postgres
      DB_USER: odoo
      DB_PASSWORD: odoo
      WORKERS: "1"
      DOCKER: "true"
    steps:
      - name: Create config file
        run: |
          create_config_file.sh
      - name: Wait for PostgreSQL
        run: |
          wait_for_postgres.sh
      - name: Initialize test db
        run: |
          ADDONS=$(manifestoo -d /odoo/custom list | grep _install | paste -sd,)
          unbuffer odoo -d odoo -i $ADDONS --stop-after-init | checklog-odoo
      - name: Run tests
        run: |
          ADDONS=$(manifestoo -d /odoo/custom --separator , list)
          unbuffer coverage run odoo -d odoo -u $ADDONS --test-enable --stop-after-init | checklog-odoo
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}